new_http_archive(
	name = "google_test",
	url = "https://github.com/google/googletest/archive/release-1.8.1.zip",
	strip_prefix = "googletest-release-1.8.1",
	build_file = "third_party/googletest.BUILD"
)