new_http_archive(
	name = "google_test",
	url = "https://github.com/google/googletest/archive/release-1.8.1.zip",
	strip_prefix = "googletest-release-1.8.1",
	build_file = "third_party/googletest.BUILD"
)

http_archive(
	name = "com_google_protobuf",
    strip_prefix = "protobuf-3.3.0",
    url = "https://github.com/google/protobuf/releases/download/v3.3.0/protobuf-cpp-3.3.0.tar.gz",
)